introducer Signer and Verifier interfaces
chainguard-dev/go-apk pull request #1
Opened 2023-04-28 15:59 UTC by imjasonh

This should help us plug in other signing/verifying implementations, possibly backed by KMS systems, in the future.

Callers of `SignIndex` will need to call `NewKeySignerVerifier` and pass that to `SignIndex`, instead of just passing the filename of the private signing key.

2023-04-28 16:10 UTC, imjasonh commented
I wonder whether this would also be a convenient time to introduce a `context.Context` to `Sign` and `Verify`, if we think there might be implementations that would take advantage of it. It's not going to get easier to add it than now.

2023-04-28 16:13 UTC, mattmoor commented on pkg/apk/sign.go
> +		return nil, errDigestNotSHA1
Some KMS interfaces support taking the data and hashing itself, and some take the data pre-hashed.  Can we adapt the method name and argument to make it clearer that this is taking/signing the SHA1?

2023-04-30 08:56 UTC, deitch requested changes
I really like what you did here @imjasonh . Actually, to the point where I am not even sure it is fair to ask for these changes. I will ask anyways, but if you push back and think they are unreasonable, we can approve and merge it in.

* I think the whole sign/verify thing should go in its own path. I know it wasn't before, but that was because it was constrained into apko's structure. Now, it has the space to do what it needs. Maybe `pkg/apk/signatures` or something like that?
* Once we do, can we put the interfaces (`Signer`, `Verifier`, `SignerVerifier`) into their own files, and then the actual impl into its own as well
* The specific `keySignerVerifier` we have here is specifically for our current needs, i.e. RSA signatures with a SHA1 digest. Should we reflect that somehow? The only reason I am not 100% sure we should is that is what is used with apk indexes for now (but that might change).

For the latter point, we either could have a separate implementation, e.g.:

```go
type rsaWithSha1KeySignerVerifier struct
...
NewRSAWithSha1KeySignerVerifier()
```

Or a generic keySignerVerifier that recognizes the formats it is passed. That could be either because it knows how to read the keys and hashes (which is a little tricky) or is passed options to `New()`.

2023-05-01 12:12 UTC, deitch commented
@imjasonh I may have complicated your PR here, my apologies. I had to move some of the signing stuff around in order to be able to extract it from melange (#15 and some subsequent ones). The structure hasn't really changed, just the location and some minor parameters. So your PR still should work, it just needs a little more than a simple rebase.

2023-05-09 08:49 UTC, deitch commented
@imjasonh any desire to get this one in?

2023-06-14 17:56 UTC, closed without merging